///////////////////////////////////////////////////////////////////////////////
// UDPClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "UDPClassFactory.h"
#include "UDPServices.h"
#include "UDPVersion.h"
#include "Module1.h"

BEGIN_CLASS_MAP(CUDPClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY_LIB(VID_UDP, CID_UDPCModule1, SRVNAME_UDP "!CModule1", CModule1)
///</AutoGeneratedContent>
END_CLASS_MAP()

CUDPClassFactory::CUDPClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME_TMX(SRVNAME_UDP));
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(UDP));
#endif //defined(TCDBG_UNIT_VERSION)
}

